#!/bin/bash
source /etc/mkm.conf

echo Signing kernel
echo ${bldblu}${txtbld}Which version?${txtrst}
read VERSION
echo ${bldred}Sigining kernel
cd ~/.keys

sudo sbsign --key MOK.priv --cert MOK.pem /boot/vmlinuz-$vbase.$VERSION-lz-xan1 --output /boot/vmlinuz-$vbase.$VERSION-lz-xan1.signed

sudo cp /boot/initrd.img-$vbase.$VERSION-lz-xan1{,.signed}
echo signed ${txtrst}

sudo -v
echo "Signing the following modules"
for filename in /lib/modules/$(uname -r)/updates/dkms/*.ko; do
    sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ~/.keys/MOK.priv ~/.keys/MOK.der $filename
    echo "$filename"
done

#Remove unsigned
sudo mv /boot/vmlinuz-$vbase.$VERSION-lz-xan1{.signed,}
sudo mv /boot/initrd.img-$vbase.$VERSION-lz-xan1{.signed,}
sudo update-grub
sudo update-initramfs -ck all

cd -

# Return to kernel menu
zenity --question --text "Anything else?"
    kernel=$?
    if [[ $kernel -eq 0 ]]; then
        lz-kernel-manager
    fi
